project/models/car.py
# Libraries
from project import db
from sqlalchemy import func


class Car(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    car_name = db.Column(db.String(10), nullable=False)
    registered_on = db.Column(db.DateTime(), server_default=func.now())

    @classmethod
    def find_one_by_car_id(cls, car_id):
        return Car.query.filter_by(id=car_id).first()

project/models/user.py
# Libraries
from project import db
from sqlalchemy import func


class User(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    user_name = db.Column(db.String(10), nullable=False)
    registered_on = db.Column(db.DateTime(), server_default=func.now())

    @classmethod
    def find_one_by_user_id(cls, user_id):
        return User.query.filter_by(id=user_id).first()

project/routes/auth_routes.py
# Libraries
from flask import Blueprint, redirect, render_template, url_for, flash, session, request, g
from werkzeug import security

# DB Models
from project.models.admin import Admin as AdminModel

# Flask Forms
from project.form.auth_form import LoginForm, RegisterForm


blueprint = Blueprint(
    'auth',
    __name__,
    url_prefix='/auth'
)

# Request Hook for entire app
@blueprint.before_app_request
def before_app_request():
    g.admin = None
    admin_name = session.get('admin_name')
    if admin_name:
        admin = AdminModel.find_one_by_admin_name(admin_name)
        if admin:
            g.admin = admin
        else:
            session.pop('admin_name', None)

# Get Login Route (Redirect)
@blueprint.route('/')
def index():
    return redirect(url_for('auth.login'))

# Get Login Route
@blueprint.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()

    # check method 'POST' and validate is OK
    if form.validate_on_submit():
        admin_name = form.data.get('admin_name')
        password = form.data.get('password')
        admin = AdminModel.find_one_by_admin_name(admin_name)
        if admin:
            if not security.check_password_hash(admin.password, password):
                flash('Password is not valid.')
            else:
                session['admin_name'] = admin.admin_name
                return redirect(url_for('base.index'))

        else:
            flash('Admin Name does not exists.')
    else:
        flash_form_errors(form)

    return render_template('login.html', form=form)

# Get Register Route
@blueprint.route('/register', methods=['GET', 'POST'])
def register():
    form = RegisterForm()

    # check method 'POST' and validate is OK
    if form.validate_on_submit():
        admin_name = form.data.get('admin_name')
        password = form.data.get('password')
        repassword = form.data.get('repassword')
        admin = AdminModel.find_one_by_admin_name(admin_name)
        if admin:
            flash('Admin Name already exists.')
            return redirect(request.path)
        else:
            g.db.add(
                AdminModel(
                    admin_name=admin_name,
                    password=security.generate_password_hash(password)
                )
            )
            g.db.commit()
            session['admin_name'] = admin_name
            return redirect(url_for('base.index'))
    else:
        flash_form_errors(form)

    return render_template('register.html', form=form)

# Get Logout Route
@blueprint.route('/logout')
def logout():
    session.pop('admin_name', None)
    return redirect(url_for('auth.login'))


def flash_form_errors(form):
    for _, errors in form.errors.items():
        for e in errors:
            flash(e)

project/routes/base_routes.py
# Libraries
from flask import Blueprint, redirect, render_template, request, g, url_for
from sqlalchemy import and_, func, or_

# DB Models
from project.models.event import Event as EventModel
from project.models.entry import Entry as EntryModel

blueprint = Blueprint(
    'base',
    __name__
)

# Get Event List Route
@blueprint.route('/')
def index():
    if not g.admin:
        return redirect(url_for('auth.login'))
    input_from = request.args.get('input_from', default='')
    input_to = request.args.get('input_to', default='')
    page = request.args.get('page', type=int ,default=1)
    needle = request.args.get('needle', type=str, default='')
    event_list = EventModel.query.filter(or_(
        EventModel.is_damaged_1 != None,
        EventModel.is_damaged_2 != None,
        EventModel.is_damaged_3 != None,
        EventModel.is_damaged_4 != None,
        EventModel.is_damaged_5 != None,
        EventModel.is_damaged_6 != None,)
    ).order_by(
        EventModel.created_on.desc()
    )

    if needle:
        event_list = event_list.filter(
            EventModel.car_id == needle
        )

    if input_from and input_to:
        event_list = event_list.filter(and_
            (func.date(EventModel.created_on) >= input_from),
            (func.date(EventModel.created_on) <= input_to)
        )
    event_list = event_list.paginate(page, per_page=10)
    return render_template('index.html', event_list=event_list, page=page)

# Get Event Detail Route
@blueprint.route('/detail/<int:id>')
def detail(id):
    if not g.admin:
        return redirect(url_for('auth.login'))
    entry = EntryModel.query.filter(EntryModel.event_id == id).first()
    if entry is None:
        return render_template('detail.html', entry=entry)
    path_inference_list = entry.path_inference_dent.split('_')[:-1]
    return render_template('detail.html', entry=entry, path_inference_list=path_inference_list)

# Get Event Inspect Route
@blueprint.route('/detail/inspect')
def inspect():
    if not g.admin:
        return redirect(url_for('auth.login'))
    path_original = request.args['path_original']
    return render_template('via.html', path_original=path_original)

# Confirm Inspection
@blueprint.route('/detail/<int:id>/confirm', methods=['POST'])
def confirm(id):
    if not g.admin:
        return redirect(url_for('auth.login'))
    if request.method == 'POST':
        inspector = request.form['inspector']
        inspected_on = func.now()
        is_inspected = True
        entry = EntryModel.query.filter(EntryModel.event_id == id).first()
        entry.inspector = inspector
        entry.inspected_on = inspected_on
        entry.is_inspected = is_inspected
        g.db.commit()
        return redirect(url_for('base.detail', id=id))

project/routes/car_routes.py
# Libraries
from flask import Blueprint, render_template, request, g, url_for
from werkzeug.utils import redirect

# DB Models
from project.models.car import Car as CarModel


blueprint = Blueprint(
    'cars',
    __name__,
    url_prefix='/cars'
)

# Get Car List Route
@blueprint.route('/')
def cars():
    if not g.admin:
        return redirect(url_for('auth.login'))
    page = request.args.get('page', type=int, default=1)
    needle = request.args.get('needle', type=str, default='')
    car_list = CarModel.query.order_by(CarModel.registered_on.desc())
    if needle:
        car_list = car_list.filter(
            CarModel.id.ilike(needle)
        )
    car_list = car_list.paginate(page, per_page=10)
    return render_template('cars.html', car_list=car_list, page=page, needle=needle)

# Register Car Route
@blueprint.route('/register', methods=['POST'])
def register():
    if not g.admin:
        return redirect(url_for('auth.login'))
    car_name = request.form['car_name']
    car = CarModel(car_name=car_name)
    g.db.add(car)
    g.db.commit()
    return redirect(url_for('cars.cars'))

# Delete Car Route
@blueprint.route('/delete', methods=['POST'])
def delete():
    if not g.admin:
        return redirect(url_for('auth.login'))
    car_id = request.form['car_id']
    car = CarModel.query.get_or_404(car_id)
    g.db.delete(car)
    g.db.commit()
    return redirect(url_for('cars.cars'))

project/routes/user_routes.py
# Libraries
from flask import Blueprint, render_template, request, g, url_for
from werkzeug.utils import redirect

# DB Models
from project.models.user import User as UserModel


blueprint = Blueprint(
    'users',
    __name__,
    url_prefix='/users'
)

# Get User List Route
@blueprint.route('/')
def users():
    if not g.admin:
        return redirect(url_for('auth.login'))
    page = request.args.get('page', type=int, default=1)
    needle = request.args.get('needle', type=str, default='')
    user_list = UserModel.query.order_by(UserModel.registered_on.desc())
    if needle:
        user_list = user_list.filter(
            UserModel.id.ilike(needle)
        )
    user_list = user_list.paginate(page, per_page=10)
    return render_template('users.html', user_list=user_list, page=page, needle=needle)

# Register User Route
@blueprint.route('/register', methods=['POST'])
def register():
    if not g.admin:
        return redirect(url_for('auth.login'))
    user_name = request.form['user_name']
    user = UserModel(user_name=user_name)
    g.db.add(user)
    g.db.commit()
    return redirect(url_for('users.users'))

# Delete User Route
@blueprint.route('/delete', methods=['POST'])
def delete():
    if not g.admin:
        return redirect(url_for('auth.login'))
    user_id = request.form['user_id']
    user = UserModel.query.get_or_404(user_id)
    g.db.delete(user)
    g.db.commit()
    return redirect(url_for('users.users'))

project/templates/_errors.html
<div class="error-message">
    {% for message in get_flashed_messages() %}
        <i class="fa-solid fa-exclamation exclamation"></i> {{ message }}
    {% endfor %}
</div>

project/templates/cars.html
<!-- CSS INIT -->
<link rel="stylesheet" href="../static/css/cars.css">

{% extends 'base.html' %}
{% block content %}

<!-- Navigation Bar -->
<nav class="navbar navbar-expand-lg navbar-dark">
    <div class="container-fluid">
        <a class="navbar-logo" href="{{ url_for('base.index') }}">
            <img class="logo" src="../static/images/favicons.ico/favicon-96x96.png" alt="Logo" height="35" width="35">
        </a>
        <a class="navbar-brand" href="{{ url_for('base.index') }}">SOLOv6</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{{ url_for('base.index') }}">HOME</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" href="{{ url_for('base.index') }}">Events</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" href="{{ url_for('cars.cars') }}">Cars</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" href="{{ url_for('users.users') }}">Users</a>
                </li>
            </ul>
            <form id="search-form" class="d-flex" action="{{ url_for('cars.cars') }}" method="get">
                <input id="needle search-needle" class="form-control me-2 search-form" type="text" name="needle" value="{{ needle or '' }}" placeholder="Car ID..." aria-label="Search" autocomplete="off">
                <input id="page" type="hidden" name="page" value=1>
                <button id="btn-search" class="btn search-btn" type="submit">
                    <i class="fa-solid fa-magnifying-glass fa-xl"></i>
                </button>
            </form>
        </div>
    </div>
</nav>
<!-- Main -->
<div class="main">
    <!-- Main_Register -->
    <div class="register-box">
        <div class="register-col">
            <form class="register-form" action="{{ url_for('cars.register') }}" method="post">
                <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
                <input class="form-control register-input" type="text" name="car_name" placeholder="Model name..." autocomplete="off">
                <button type="submit" class="btn btn-primary mb-3 register-btn">
                    Register
                </button>
            </form>
        </div>
        <div class="dropdown">
            <button class="btn btn-light dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
                Latest v1.0.0
            </button>
            <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                <li><a class="dropdown-item" href="#">v1.0.0</a></li>
            </ul>
        </div>
    </div>

    <!-- Main_List -->
    <div class="container list-box">
        <div class="row list-title-box border-bottom">
            <div class="col list-title my-3">
                Car ID
            </div>
            <div class="col list-title my-3">
                Car Name
            </div>
            <div class="col list-title my-3">
                Registered On
            </div>
        </div>
        {% if car_list %}
            {% for car in car_list.items %}
            <div class="card my-2">
                <div class="card-body">
                    <div class="row card-body-row">
                        <div class="col list-col">
                            {{ car.id }}
                        </div>
                        <div class="col list-col">
                            {{ car.car_name }}
                        </div>
                        <div class="col list-col">
                            {{ car.registered_on }}
                            <div class="cancel-box">
                                <form class="delete-form" action="{{ url_for('cars.delete') }}" method="post">
                                    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
                                    <input class="delete-car-id-input" type="hidden" name="car_id" value="{{ car.id }}">
                                    <button type="submit" class="btn btn-danger mb-3 cancel-btn">
                                        <i class="fa-solid fa-xmark"></i>
                                    </button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        {% else %}
        <div class="row">
            <div class="col-12">
                <h2>❌ No Car Registered ❌</h2>
            </div>
        </div>
        {% endif %}
    </div>
</div>

<!-- Pagination -->
<ul class="pagination my-4 justify-content-center">
    {% if car_list.has_prev %}
    <li class="page-item">
        <a class="page-link" href="?page={{ car_list.prev_num }}">Previous</a>
    </li>
    {% else %}
    <li class="page-item disabled">
        <a class="page-link" tabindex="-1" aria-disabled="true" href="javascript:void(0)">Previous</a>
    </li>
    {% endif %}
    {% for page_num in car_list.iter_pages() %}
    {% if page_num %}
    {% if page_num != car_list.page %}
    <li class="page-item">
        <a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a>
    </li>
    {% else %}
    <li class="page-item active" aria-current="page">
        <a class="page-link" href="javascript:void(0)">{{ page_num }}</a>
    </li>
    {% endif %}
    {% else %}
    <li class="disabled">
        <a class="page-link" href="javascript:void(0)">...</a>
    </li>
    {% endif %}
    {% endfor %}
    {% if car_list.has_next %}
    <li class="page-item">
        <a class="page-link" href="?page={{ car_list.next_num }}">Next</a>
    </li>
    {% else %}
    <li class="page-item disabled">
        <a class="page-link" tabindex="-1" aria-disabled="true" href="javascript:void(0)">Next</a>
    </li>
    {% endif %}
</ul>
{% endblock %}
{% block script %}
<script type="text/javascript">
    const btn_search = document.getElementById('btn-search');
    btn_search.addEventListener('click', function() {
        document.getElementById('needle').value = document.getElementById('search-needle').value;
        document.getElementById('page').value = 1;
        document.getElementById('search-form').submit();
    });
</script>
{% endblock %}

project/templates/detail.html
{% extends 'base.html' %}
{% block head %}
<!-- CSS INIT -->
<link rel="stylesheet" href="../static/css/detail.css">
{% endblock %}

{% block content %}
<!-- Navigation Bar -->
<nav class="navbar navbar-expand-lg navbar-dark">
    <div class="container-fluid">
        <a class="navbar-logo" href="{{ url_for('base.index') }}">
            <img class="logo" src="../static/images/favicons.ico/favicon-96x96.png" alt="Logo" height="35" width="35">
        </a>
        <a class="navbar-brand" href="{{ url_for('base.index') }}">SOLOv6</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{{ url_for('base.index') }}">HOME</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" href="{{ url_for('base.index') }}">Events</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" href="{{ url_for('cars.cars') }}">Cars</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" href="{{ url_for('users.users') }}">Users</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

{% if entry %}
<!-- Main -->
<div class="main">
    <!-- Main_Header -->
    <div class="header-box">
        <div class="header-row">
            <div class="header-col">
                <h3 class="header-title fs-2">Event Dashboard</h3>
            </div>
        </div>
    </div>

    <!-- Main_Content -->
    <div class="container main-content">
        <div class="card detail-box mt-3">
            <div class="detail-box-body">
                <div class="detail-box-left">
                    <h2 class="detail-box-title event-id card-info"><strong>Event ID :</strong> {{ entry.event.id }}</h2>
                    <h4 class="detail-box-subtitle mb-2 text-muted event-date card-info"><strong>Date :</strong> {{ entry.event.created_on }}</h4>
                    <h4 class="detail-box-text text-muted event-user card-info">
                        <strong>User ID :</strong> {{ entry.event.user_id }}<br>
                        <strong>Car ID :</strong> {{ entry.event.car_id }}
                    </h4>
                </div>
                <div class="detail-box-right">
                    <div class="inspected-on-box">
                        <h4 class="inspected-on-box-title">Inspected On</h4>
                        {% if entry.inspected_on %}
                        <h5 class="inspected-on-box-text">{{ entry.inspected_on }}</h5>
                        {% else %}
                        <h5 class="inspected-on-box-text">-</h5>
                        {% endif %}
                    </div>
                    <div class="inspector-box">
                        <h4 class="inspector-box-title">Inspector</h4>
                        {% if entry.inspector %}
                        <h5 class="inspector-box-text">{{ entry.inspector }}</h5>
                        {% else %}
                        <h5 class="inspector-box-text">-</h5>
                        {% endif %}
                    </div>
                    <div class="inspector-box-status">
                        <h4 class="inspector-box-status-title">Status</h4>
                        {% if entry.is_inspected %}
                        <h5 class="inspector-box-status-text confirm-disabled">Confirmed! <i class="fa-solid fa-check check-icon"></i></h5>
                        {% else %}
                        <form action="{{ url_for('base.confirm', id=entry.event.id) }}" method="post">
                            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
                            <input class="inspector-input" type="hidden" name="inspector" value="{{ g.admin.admin_name }}">
                            <button type="submit" class="btn mb-3 btn-success confirm-btn">
                                Confirmed! <i class="fa-solid fa-check check-icon"></i>
                            </button>
                        </form>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
        <div class="info-box mt-3 mb-4">
            <div class="info-image-box ps-4 pe-4">
                <div class="row info-image-box-row mt-2">
                    <div class="col-2 info-image-box-col ms-3">dent</div>
                    <div class="col-2 info-image-box-col ms-2">scratch</div>
                    <div class="col-2 info-image-box-col ms-1 me-5">spacing</div>
                    <div class="col-2 info-image-box-col ms-3">is_damaged</div>
                    <div class="col-2 info-image-box-col ms-5">inspect</div>
                </div>
                {% for path_inference in path_inference_list %}
                <div class="content-box mt-2 mb-2">
                    <div class="card mb-3 ms-2 me-2 mt-3 image-card">
                        <img src="https://storage.googleapis.com/solov6-test-storage/path_inference_dent/{{ path_inference }}.jpeg" class="card-img-top" alt="{{ path_inference }}.jpeg">
                    </div>
                    <div class="card mb-3 ms-2 me-2 mt-3 image-card">
                        <img src="https://storage.googleapis.com/solov6-test-storage/path_inference_scratch/{{ path_inference }}.jpeg" class="card-img-top" alt="{{ path_inference }}.jpeg">
                    </div>
                    <div class="card mb-3 ms-2 me-5 mt-3 image-card">
                        <img src="https://storage.googleapis.com/solov6-test-storage/path_inference_spacing/{{ path_inference }}.jpeg" class="card-img-top" alt="{{ path_inference }}.jpeg">
                    </div>
                    <div class="is_damaged-box">
                        {% if loop.index == 1 %}
                        <h4>{{ entry.event.is_damaged_1 }}</h4>
                        {% elif loop.index == 2 %}
                        <h4>{{ entry.event.is_damaged_2 }}</h4>
                        {% elif loop.index == 3 %}
                        <h4>{{ entry.event.is_damaged_3 }}</h4>
                        {% elif loop.index == 4 %}
                        <h4>{{ entry.event.is_damaged_4 }}</h4>
                        {% elif loop.index == 5 %}
                        <h4>{{ entry.event.is_damaged_5 }}</h4>
                        {% elif loop.index == 6 %}
                        <h4>{{ entry.event.is_damaged_6 }}</h4>
                        {% endif %}
                    </div>
                    {% if entry.is_inspected %}
                    <div class="inspect-box">
                        <form class="inspect-form" action="#" method="get">
                            <button type="button" class="btn btn-primary inspect-btn" disabled>
                                Inspect
                            </button>
                        </form>
                    </div>
                    {% else %}
                    <div class="inspect-box">
                        <form class="inspect-form" action="{{ url_for('base.inspect') }}" method="get">
                            <input class="inspect-path-original" type="hidden" name="path_original" value="{{ path_inference }}.jpeg">
                            <button type="submit" class="btn btn-primary mb-3 inspect-btn">
                                Inspect
                            </button>
                        </form>
                    </div>
                    {% endif %}
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
{% else %}
<!-- Main -->
<div class="main">
    <!-- Main_Header -->
    <div class="header-box">
        <div class="header-row">
            <div class="header-col">
                <h3 class="header-title fs-2">Event Dashboard</h3>
            </div>
        </div>
    </div>

    <!-- Main_Content -->
    <div class="container">
        <div class="detail-box">
            <h3 class="event-id message mt-5 mb-5">No damage detected.</h3>
        </div>
    </div>
</div>
{% endif %}
{% endblock %}

project/templates/users.html
<!-- CSS INIT -->
<link rel="stylesheet" href="../static/css/users.css">

{% extends 'base.html' %}
{% block content %}

<!-- Navigation Bar -->
<nav class="navbar navbar-expand-lg navbar-dark">
    <div class="container-fluid">
        <a class="navbar-logo" href="{{ url_for('base.index') }}">
            <img class="logo" src="../static/images/favicons.ico/favicon-96x96.png" alt="Logo" height="35" width="35">
        </a>
        <a class="navbar-brand" href="{{ url_for('base.index') }}">SOLOv6</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{{ url_for('base.index') }}">HOME</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" href="{{ url_for('base.index') }}">Events</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" href="{{ url_for('cars.cars') }}">Cars</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" href="{{ url_for('users.users') }}">Users</a>
                </li>
            </ul>
            <form id="search-form" class="d-flex" action="{{ url_for('users.users') }}" method="get">
                <input id="needle search-needle" class="form-control me-2 search-form" type="text" name="needle" value="{{ needle or '' }}" placeholder="User ID..." aria-label="Search" autocomplete="off">
                <input id="page" type="hidden" name="page" value=1>
                <button id="btn-search" class="btn search-btn" type="submit">
                    <i class="fa-solid fa-magnifying-glass fa-xl"></i>
                </button>
            </form>
        </div>
    </div>
</nav>

<!-- Main -->
<div class="main">
    <!-- Main_Register -->
    <div class="register-box">
        <div class="register-col">
            <form class="register-form" action="{{ url_for('users.register') }}" method="post">
                <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
                <input class="form-control register-input" type="text" name="user_name" placeholder="User name..." autocomplete="off">
                <button type="submit" class="btn btn-primary mb-3 register-btn">
                    Register
                </button>
            </form>
        </div>
        <div class="dropdown">
            <button class="btn btn-light dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
                Latest v1.0.0
            </button>
            <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                <li><a class="dropdown-item" href="#">v1.0.0</a></li>
            </ul>
        </div>
    </div>

    <!-- Main_List -->
    <div class="container list-box">
        <div class="row list-title-box border-bottom">
            <div class="col list-title my-3">
                User ID
            </div>
            <div class="col list-title my-3">
                User Name
            </div>
            <div class="col list-title my-3">
                Registered On
            </div>
        </div>
        {% if user_list %}
            {% for user in user_list.items %}
            <div class="card my-2">
                <div class="card-body">
                    <div class="row card-body-row">
                        <div class="col list-col">
                            {{ user.id }}
                        </div>
                        <div class="col list-col">
                            {{ user.user_name }}
                        </div>
                        <div class="col list-col">
                            {{ user.registered_on }}
                            <div class="cancel-box">
                                <form class="delete-form" action="{{ url_for('users.delete') }}" method="post">
                                    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
                                    <input class="delete-user-id-input" type="hidden" name="user_id" value="{{ user.id }}">
                                    <button type="submit" class="btn btn-danger mb-3 cancel-btn">
                                        <i class="fa-solid fa-xmark"></i>
                                    </button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        {% else %}
        <div class="row">
            <div class="col-12">
                <h2>❌ No User Registered ❌</h2>
            </div>
        </div>
        {% endif %}
    </div>
</div>

<!-- Pagination -->
<ul class="pagination my-4 justify-content-center">
    {% if user_list.has_prev %}
    <li class="page-item">
        <a class="page-link" href="?page={{ user_list.prev_num }}">Previous</a>
    </li>
    {% else %}
    <li class="page-item disabled">
        <a class="page-link" tabindex="-1" aria-disabled="true" href="javascript:void(0)">Previous</a>
    </li>
    {% endif %}
    {% for page_num in user_list.iter_pages() %}
    {% if page_num %}
    {% if page_num != user_list.page %}
    <li class="page-item">
        <a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a>
    </li>
    {% else %}
    <li class="page-item active" aria-current="page">
        <a class="page-link" href="javascript:void(0)">{{ page_num }}</a>
    </li>
    {% endif %}
    {% else %}
    <li class="disabled">
        <a class="page-link" href="javascript:void(0)">...</a>
    </li>
    {% endif %}
    {% endfor %}
    {% if user_list.has_next %}
    <li class="page-item">
        <a class="page-link" href="?page={{ user_list.next_num }}">Next</a>
    </li>
    {% else %}
    <li class="page-item disabled">
        <a class="page-link" tabindex="-1" aria-disabled="true" href="javascript:void(0)">Next</a>
    </li>
    {% endif %}
</ul>
{% endblock %}
{% block script %}
<script type="text/javascript">
    const btn_search = document.getElementById('btn-search');
    btn_search.addEventListener('click', function() {
        document.getElementById('needle').value = document.getElementById('search-needle').value;
        document.getElementById('page').value = 1;
        document.getElementById('search-form').submit();
    });
</script>
{% endblock %}